# Generated by Django 4.2.16 on 2025-07-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_paymentinfo_application_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('membership_type', models.CharField(blank=True, choices=[('regular', 'Regular'), ('exclusive', 'Exclusive'), ('vip', 'VIP')], max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=10, null=True)),
                ('signature_photo', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('utr_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.paymentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_tenure', models.CharField(max_length=20)),
                ('loan_purpose', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('pan', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('nominee1_name', models.CharField(max_length=100)),
                ('nominee1_mobile', models.CharField(max_length=10)),
                ('nominee1_aadhar', models.CharField(max_length=12)),
                ('nominee2_name', models.CharField(max_length=100)),
                ('nominee2_mobile', models.CharField(max_length=10)),
                ('nominee2_aadhar', models.CharField(max_length=12)),
                ('supporting_document_type', models.CharField(max_length=100)),
                ('supporting_document', models.FileField(upload_to='loan_documents/')),
                ('other_docs_explain', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.member')),
            ],
        ),
    ]
