# Generated by Django 4.2.16 on 2025-06-28 06:33

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(default=authentication.models.generate_custom_uuid, editable=False, max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('utr_id', models.CharField(max_length=100, unique=True)),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='authentication.paymentinfo')),
            ],
        ),
    ]
