# Generated by Django 4.2.16 on 2025-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='application_fees',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
