# Generated by Django 4.2.16 on 2025-06-28 06:33

from django.db import migrations, models
import django.db.models.deletion
import scholarship.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=9)),
                ('query_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('uuid', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('aadhar_card_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('aadhar_photo', models.ImageField(blank=True, null=True, upload_to=scholarship.models.upload_to)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[scholarship.models.validate_phone_number])),
                ('password', models.CharField(max_length=128)),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluk', models.CharField(blank=True, max_length=100, null=True)),
                ('board_of_education', models.CharField(blank=True, max_length=100, null=True)),
                ('present_class', models.CharField(blank=True, max_length=50, null=True)),
                ('marks_obtained', models.CharField(blank=True, max_length=50, null=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to=scholarship.models.upload_to)),
                ('study_certificate_photo', models.ImageField(blank=True, null=True, upload_to=scholarship.models.upload_to)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to=scholarship.models.upload_to)),
                ('utr_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('passbook_photo', models.ImageField(blank=True, null=True, upload_to=scholarship.models.upload_to)),
                ('agentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='authentication.paymentinfo')),
            ],
        ),
    ]
